import { MongoClient } from "mongodb";

const uri = process.env.MONGODB_URI;
if (!uri) {
  console.error("MONGODB_URI is not set");
  process.exit(1);
}
const connectionString = String(uri);

async function seed() {
  const client = new MongoClient(connectionString);
  try {
    await client.connect();
    const db = client.db("culturechain");
    console.log("Connected to MongoDB");

    // --- ARTISANAL CRAFTS ---
    const craftsCol = db.collection("crafts");
    await craftsCol.deleteMany({});
    await craftsCol.insertMany([
      {
        craftId: "craft-001",
        name: "Masque Baoule Goli",
        description: "Masque sacre de la danse Goli, sculpte a la main par les maitres artisans Baoule. Ce masque represente l'esprit protecteur du village et est utilise lors des ceremonies de rejouissance.",
        artisan: "Maitre Kouassi Yao",
        origin: "Region du Gbeke, Bouake",
        culture: "Baoule",
        category: "masque",
        image: "/images/artisan-mask.jpg",
        price: 75000,
        rating: 4.9,
        reviews: 42,
        nftCertified: true,
        tokenId: "0xcraft01...a1b2",
        merkleRoot: "0xcr01...def1",
        inStock: true,
        createdAt: new Date("2025-06-15"),
      },
      {
        craftId: "craft-002",
        name: "Tissu Kente Senoufo",
        description: "Tissu traditionnel tisse a la main par les tisserands Senoufo du nord de la Cote d'Ivoire. Chaque motif raconte une histoire et porte un message symbolique ancestral.",
        artisan: "Coulibaly Naminata",
        origin: "Korhogo, Region du Poro",
        culture: "Senoufo",
        category: "textile",
        image: "/images/artisan-textile.jpg",
        price: 45000,
        rating: 4.7,
        reviews: 38,
        nftCertified: true,
        tokenId: "0xcraft02...c3d4",
        merkleRoot: "0xcr02...abc2",
        inStock: true,
        createdAt: new Date("2025-08-20"),
      },
      {
        craftId: "craft-003",
        name: "Poterie Bete Traditionnelle",
        description: "Jarre decorative en terre cuite realisee selon les techniques ancestrales Bete. Ornee de motifs geometriques symbolisant la fertilite et la prosperite.",
        artisan: "Guehi Marie-Therese",
        origin: "Daloa, Region du Haut-Sassandra",
        culture: "Bete",
        category: "poterie",
        image: "/images/artisan-pottery.jpg",
        price: 25000,
        rating: 4.5,
        reviews: 22,
        nftCertified: true,
        tokenId: "0xcraft03...e5f6",
        merkleRoot: "0xcr03...ghi3",
        inStock: true,
        createdAt: new Date("2025-09-10"),
      },
      {
        craftId: "craft-004",
        name: "Statuette Senoufo Deble",
        description: "Statuette rituelle en bois d'iroko sculptee par les Senoufo. Utilisee dans les ceremonies du Poro, elle represente la beaute feminine ideale et la sagesse.",
        artisan: "Soro Daouda",
        origin: "Boundiali, Region de la Bagoue",
        culture: "Senoufo",
        category: "sculpture",
        image: "/images/artisan-sculpture.jpg",
        price: 120000,
        rating: 4.8,
        reviews: 15,
        nftCertified: true,
        tokenId: "0xcraft04...g7h8",
        merkleRoot: "0xcr04...jkl4",
        inStock: true,
        createdAt: new Date("2025-07-05"),
      },
      {
        craftId: "craft-005",
        name: "Bijoux en Or Akan",
        description: "Parure traditionnelle en bronze dore realisee par les orfevres Akan. Comprend un collier et des bracelets avec des motifs symboliques representant la royaute.",
        artisan: "Konan Affoue",
        origin: "Abengourou, Region de l'Indenie-Djuablin",
        culture: "Akan",
        category: "bijoux",
        image: "/images/artisan-jewelry.jpg",
        price: 95000,
        rating: 4.6,
        reviews: 29,
        nftCertified: true,
        tokenId: "0xcraft05...i9j0",
        merkleRoot: "0xcr05...mno5",
        inStock: true,
        createdAt: new Date("2025-10-01"),
      },
      {
        craftId: "craft-006",
        name: "Djembe Dioula Ceremonial",
        description: "Djembe traditionnel sculpte dans un tronc de lenke, monte avec une peau de chevre. Instrument sacre utilise lors des fetes et ceremonies Dioula.",
        artisan: "Bakayoko Sekou",
        origin: "Odienne, Region du Kabadougou",
        culture: "Dioula",
        category: "instrument",
        image: "/images/artisan-drum.jpg",
        price: 65000,
        rating: 4.7,
        reviews: 34,
        nftCertified: true,
        tokenId: "0xcraft06...k1l2",
        merkleRoot: "0xcr06...pqr6",
        inStock: true,
        createdAt: new Date("2025-11-15"),
      },
    ]);
    await craftsCol.createIndex({ craftId: 1 }, { unique: true });
    console.log("Crafts seeded");

    // --- GUIDED TOURS ---
    const toursCol = db.collection("tours");
    await toursCol.deleteMany({});
    await toursCol.insertMany([
      {
        tourId: "tour-001",
        siteId: "grand-bassam",
        siteName: "Grand-Bassam",
        title: "Visite Historique Coloniale",
        description: "Parcourez les rues historiques de Grand-Bassam avec un guide expert. Decouvrez l'architecture coloniale, le musee du costume et l'histoire fascinante de l'ancienne capitale.",
        guide: "Koffi Jean-Baptiste",
        guideId: "guide-001",
        duration: "3h",
        maxParticipants: 15,
        currentParticipants: 8,
        price: 15000,
        date: "2026-03-15",
        time: "09:00",
        language: "Francais",
        includes: ["Guide certifie", "Entree musee", "Rafraichissements"],
        rating: 4.9,
        status: "available",
      },
      {
        tourId: "tour-002",
        siteId: "basilique",
        siteName: "Basilique Notre-Dame de la Paix",
        title: "Decouverte Architecturale",
        description: "Explorez la plus grande basilique du monde avec une guide specialisee en architecture religieuse. Visite des vitraux, de la crypte et des jardins.",
        guide: "Diallo Aminata",
        guideId: "guide-002",
        duration: "2h30",
        maxParticipants: 20,
        currentParticipants: 14,
        price: 20000,
        date: "2026-03-16",
        time: "10:00",
        language: "Francais",
        includes: ["Guide certifie", "Entree basilique", "Brochure souvenir"],
        rating: 4.8,
        status: "available",
      },
      {
        tourId: "tour-003",
        siteId: "parc-tai",
        siteName: "Parc National de Tai",
        title: "Safari Ecotouristique",
        description: "Randonnee guidee dans la foret tropicale primaire. Observation des chimpanzes, decouverte de la flore endemique et sensibilisation a la conservation.",
        guide: "Ouattara Moussa",
        guideId: "guide-003",
        duration: "6h",
        maxParticipants: 10,
        currentParticipants: 3,
        price: 35000,
        date: "2026-03-20",
        time: "07:00",
        language: "Francais",
        includes: ["Guide ecotourisme", "Equipement", "Dejeuner inclus", "Transport local"],
        rating: 4.7,
        status: "available",
      },
      {
        tourId: "tour-004",
        siteId: "mosquee-kong",
        siteName: "Mosquee de Kong",
        title: "Patrimoine Islamique du Nord",
        description: "Decouvrez l'heritage islamique de Kong avec une visite de la mosquee historique, du marche traditionnel et des ateliers d'artisans locaux.",
        guide: "Yao Akissi",
        guideId: "guide-004",
        duration: "4h",
        maxParticipants: 12,
        currentParticipants: 5,
        price: 12000,
        date: "2026-03-22",
        time: "08:30",
        language: "Francais",
        includes: ["Guide local", "Visite mosquee", "The traditionnel"],
        rating: 4.5,
        status: "available",
      },
      {
        tourId: "tour-005",
        siteId: "parc-comoe",
        siteName: "Parc National de la Comoe",
        title: "Grande Randonnee Savane",
        description: "Expedition de decouverte dans le plus grand parc d'Afrique de l'Ouest. Observation de la faune sauvage : elephants, hippopotames, antilopes.",
        guide: "Ouattara Moussa",
        guideId: "guide-003",
        duration: "8h",
        maxParticipants: 8,
        currentParticipants: 6,
        price: 45000,
        date: "2026-03-25",
        time: "06:00",
        language: "Francais",
        includes: ["Guide ecotourisme", "Transport 4x4", "Petit-dejeuner", "Dejeuner", "Jumelles"],
        rating: 4.6,
        status: "available",
      },
    ]);
    await toursCol.createIndex({ tourId: 1 }, { unique: true });
    console.log("Tours seeded");

    // --- STORIES (Storytelling/Promotion) ---
    const storiesCol = db.collection("stories");
    await storiesCol.deleteMany({});
    await storiesCol.insertMany([
      {
        storyId: "story-001",
        title: "Les Masques Sacres du Peuple Baoule",
        excerpt: "Plongez dans l'univers mystique des masques Goli et Gba Gba, gardiens des traditions ancestrales Baoule.",
        content: "Les masques Baoule sont bien plus que de simples objets d'art. Ils incarnent les esprits ancestraux et jouent un role central dans la vie spirituelle et sociale du peuple Baoule. Le masque Goli, avec ses formes rondes et son sourire enigmatique, est utilise lors des ceremonies de rejouissance et de deuil. Il apparait toujours par paire, symbolisant la dualite de l'univers. Les danses du Goli sont accompagnees de chants et de rythmes de tambours qui font vibrer toute la communaute. La transmission de cet art se fait de maitre a apprenti, dans le secret des bosques sacres.",
        culture: "Baoule",
        category: "traditions",
        image: "/images/artisan-mask.jpg",
        author: "Dr. Kouame N'Guessan",
        publishedAt: new Date("2026-01-15"),
        readTime: 8,
        rating: 4.8,
        reviewCount: 24,
        featured: true,
      },
      {
        storyId: "story-002",
        title: "L'Art du Tissage Senoufo : Un Heritage Vivant",
        excerpt: "Decouvrez comment les tisserands de Korhogo perpetuent un savoir-faire millenaire a travers le tissu Kente.",
        content: "Dans le nord de la Cote d'Ivoire, les tisserands Senoufo maintiennent vivante une tradition vieille de plusieurs siecles. Le tissage du Kente n'est pas un simple artisanat - c'est un langage. Chaque motif, chaque couleur porte un message. Le blanc symbolise la purete, le vert la fertilite, l'or la royaute. Les femmes Senoufo preparent les fils de coton, tandis que les hommes travaillent sur les metiers a tisser traditionnels. Un seul tissu peut necessiter plusieurs semaines de travail minutieux. Aujourd'hui, face a la mondialisation, ces artisans s'adaptent tout en preservant l'authenticite de leur art.",
        culture: "Senoufo",
        category: "artisanat",
        image: "/images/artisan-textile.jpg",
        author: "Pr. Coulibaly Mariam",
        publishedAt: new Date("2026-01-28"),
        readTime: 6,
        rating: 4.7,
        reviewCount: 18,
        featured: true,
      },
      {
        storyId: "story-003",
        title: "Le Poro : Initiation et Sagesse Senoufo",
        excerpt: "Le Poro est l'institution initiatique la plus importante des Senoufo, formant les jeunes a devenir des adultes responsables.",
        content: "Le Poro est bien plus qu'un rite de passage - c'est une veritable universite traditionnelle qui dure 21 ans, divisee en trois cycles de 7 ans. Les jeunes Senoufo y apprennent les valeurs fondamentales de leur societe : le respect des anciens, la solidarite, le courage et la connaissance des plantes medicinales. Le bois sacre, lieu ou se deroulent les ceremonies, est un espace inviolable ou seuls les inities peuvent penetrer. Les masques et les statuettes jouent un role essentiel dans les rituels du Poro, servant de mediateurs entre le monde visible et invisible.",
        culture: "Senoufo",
        category: "spiritualite",
        image: "/images/artisan-sculpture.jpg",
        author: "Prof. Soro Kigbafori",
        publishedAt: new Date("2026-02-05"),
        readTime: 10,
        rating: 4.9,
        reviewCount: 31,
        featured: false,
      },
      {
        storyId: "story-004",
        title: "La Poterie Bete : Terre et Memoire",
        excerpt: "Les potieres Bete transforment l'argile en oeuvres d'art chargees de symboles et de memoire collective.",
        content: "Dans la region de Daloa, les femmes Bete pratiquent la poterie depuis des generations. Chaque jarre, chaque bol est modele a la main, sans tour de potier, en utilisant des techniques transmises de mere en fille. L'argile est preparee avec soin, melangee a du sable fin et a des fibres vegetales pour lui donner resistance et beaute. Les motifs geometriques graves sur les poteries ne sont pas decoratifs - ils racontent l'histoire de la famille, du clan, de la communaute. La cuisson se fait en plein air, dans un foyer de bois et de paille, a des temperatures precisement controlees par l'experience des artisanes.",
        culture: "Bete",
        category: "artisanat",
        image: "/images/artisan-pottery.jpg",
        author: "Dr. Guehi Ange",
        publishedAt: new Date("2026-02-12"),
        readTime: 7,
        rating: 4.6,
        reviewCount: 15,
        featured: false,
      },
      {
        storyId: "story-005",
        title: "L'Or des Akan : Orfevrerie et Pouvoir Royal",
        excerpt: "L'or a toujours occupe une place centrale dans la culture Akan, symbolisant le pouvoir divin des rois.",
        content: "Les Akan de Cote d'Ivoire et du Ghana ont developpe un art de l'orfevrerie sans egal en Afrique de l'Ouest. Les poids a peser l'or, les bijoux royaux et les insignes de pouvoir temoignent d'un savoir-faire extraordinaire. Chaque piece est realisee a la cire perdue, une technique qui permet une precision remarquable dans les details. Les motifs representent des proverbes, des animaux totems ou des symboles cosmiques. L'or n'est pas seulement un metal precieux pour les Akan - il est considere comme le sang de la terre, un don des ancetres qu'il faut traiter avec respect.",
        culture: "Akan",
        category: "traditions",
        image: "/images/artisan-jewelry.jpg",
        author: "Pr. Konan Ahou",
        publishedAt: new Date("2026-02-18"),
        readTime: 9,
        rating: 4.8,
        reviewCount: 27,
        featured: true,
      },
      {
        storyId: "story-006",
        title: "Le Djembe Dioula : Le Tambour qui Parle",
        excerpt: "Le djembe est bien plus qu'un instrument de musique - c'est un moyen de communication ancestral du peuple Dioula.",
        content: "Dans la tradition Dioula, le djembe est un instrument sacre capable de transmettre des messages a travers les villages. Les maitres djembefola (joueurs de djembe) sont des personnages respectes qui connaissent les rythmes specifiques pour chaque occasion : naissance, mariage, deuil, recolte, guerre. La fabrication d'un djembe est elle-meme un rituel. L'arbre choisi (generalement un lenke) est abattu avec des prieres et des offrandes. Le tronc est evide patiemment, puis la peau de chevre est montee et accordee. Un bon djembe peut produire trois sons distincts : le ton (grave), le claque (aigu) et la basse (profond).",
        culture: "Dioula",
        category: "musique",
        image: "/images/artisan-drum.jpg",
        author: "Dr. Bakayoko Issa",
        publishedAt: new Date("2026-02-25"),
        readTime: 8,
        rating: 4.7,
        reviewCount: 21,
        featured: false,
      },
    ]);
    await storiesCol.createIndex({ storyId: 1 }, { unique: true });
    console.log("Stories seeded");

    // --- REVIEWS ---
    const reviewsCol = db.collection("reviews");
    await reviewsCol.deleteMany({});
    await reviewsCol.insertMany([
      {
        reviewId: "rev-001",
        targetType: "site",
        targetId: "grand-bassam",
        targetName: "Grand-Bassam",
        authorName: "Jean-Pierre Kouadio",
        authorEmail: "touriste@mail.ci",
        rating: 5,
        comment: "Magnifique site historique ! Le guide etait passionnant et la ville coloniale est tres bien conservee. A ne pas manquer !",
        createdAt: new Date("2026-02-20"),
      },
      {
        reviewId: "rev-002",
        targetType: "site",
        targetId: "basilique",
        targetName: "Basilique Notre-Dame de la Paix",
        authorName: "Aminata Traore",
        authorEmail: "aminata.t@mail.ci",
        rating: 5,
        comment: "Impressionnant ! La basilique est encore plus grandiose en vrai qu'en photos. Les vitraux sont a couper le souffle.",
        createdAt: new Date("2026-02-18"),
      },
      {
        reviewId: "rev-003",
        targetType: "craft",
        targetId: "craft-001",
        targetName: "Masque Baoule Goli",
        authorName: "Marc Dupont",
        authorEmail: "marc.d@mail.fr",
        rating: 5,
        comment: "Piece exceptionnelle ! La certification blockchain m'a totalement rassure sur l'authenticite. Merci a Maitre Kouassi pour son travail.",
        createdAt: new Date("2026-02-15"),
      },
      {
        reviewId: "rev-004",
        targetType: "tour",
        targetId: "tour-003",
        targetName: "Safari Ecotouristique - Parc de Tai",
        authorName: "Sophie Martin",
        authorEmail: "sophie.m@mail.fr",
        rating: 4,
        comment: "Experience inoubliable ! Nous avons vu des chimpanzes de tres pres. Le guide Moussa connait la foret comme sa poche.",
        createdAt: new Date("2026-02-22"),
      },
      {
        reviewId: "rev-005",
        targetType: "craft",
        targetId: "craft-002",
        targetName: "Tissu Kente Senoufo",
        authorName: "Fatou Bamba",
        authorEmail: "fatou.b@mail.ci",
        rating: 5,
        comment: "La qualite du tissage est remarquable. Chaque motif a une signification que l'artisane m'a expliquee. Un vrai tresor culturel.",
        createdAt: new Date("2026-02-10"),
      },
    ]);
    console.log("Reviews seeded");

    console.log("Crafts, tours, stories, and reviews seed complete!");
  } catch (err) {
    console.error("Seed error:", err);
    process.exit(1);
  } finally {
    await client.close();
  }
}

seed();
